spring.application.name=midestinobd

server.port=${PORT:9999}
app.base-url=${APP_BASE_URL:http://localhost:9999}

spring.datasource.url=${MYSQL_URL:jdbc:mysql://localhost:3306/midestinobd}
spring.datasource.username=${MYSQL_USER:root}
spring.datasource.password=${MYSQL_PASSWORD:root}

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# Configuración de Groq Cloud
groq.api-key=${GROQ_API_KEY:}
groq.model=${GROQ_MODEL:llama-3.3-70b-versatile}

# Credenciales PayU Sandbox
payu.api-key=${PAYU_API_KEY:4Vj8eK4rloUd272L48hsrarnUA}
payu.merchant-id=${PAYU_MERCHANT_ID:508029}
payu.account-id=${PAYU_ACCOUNT_ID:512321}